use serde::de::Deserializer;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Debug, Deserialize, Serialize, PartialEq, Eq, Default)]
pub enum StreetNamePostType {
    ALLEY,
    ANEX,
    ARCADE,
    AVENUE,
    BAYOU,
    BEACH,
    BEND,
    BLUFF,
    BLUFFS,
    BOTTOM,
    BOULEVARD,
    BRANCH,
    BRIDGE,
    BROOK,
    BROOKS,
    BURG,
    BURGS,
    BYPASS,
    CAMP,
    CANYON,
    CAPE,
    CAUSEWAY,
    CENTER,
    CENTERS,
    CIRCLE,
    CIRCLES,
    CLIFF,
    CLIFFS,
    CLUB,
    COMMON,
    COMMONS,
    CORNER,
    CORNERS,
    COURSE,
    COURT,
    COURTS,
    COVE,
    COVES,
    CREEK,
    CRESCENT,
    CREST,
    CROSSING,
    CROSSROAD,
    CROSSROADS,
    CURVE,
    CUTOFF,
    DALE,
    DAM,
    DIVIDE,
    DRIVE,
    #[serde(rename(deserialize = "DRIVE CUTOFF"))]
    DriveCutoff,
    DRIVES,
    ESTATE,
    ESTATES,
    EXPRESSWAY,
    EXTENSION,
    EXTENSIONS,
    FALL,
    FALLS,
    FERRY,
    FIELD,
    FIELDS,
    FLAT,
    FLATS,
    FORD,
    FORDS,
    FOREST,
    FORGE,
    FORGES,
    FORK,
    FORKS,
    FORT,
    FREEWAY,
    GARDEN,
    GARDENS,
    GATEWAY,
    GLEN,
    GLENS,
    GREEN,
    GREENS,
    GROVE,
    GROVES,
    HARBOR,
    HARBORS,
    HAVEN,
    HEIGHTS,
    HIGHWAY,
    HILL,
    HILLS,
    HOLLOW,
    INLET,
    ISLAND,
    ISLANDS,
    ISLE,
    JUNCTION,
    JUNCTIONS,
    KEY,
    KEYS,
    KNOLL,
    KNOLLS,
    LAKE,
    LAKES,
    LAND,
    LANDING,
    LANE,
    LIGHT,
    LIGHTS,
    LOAF,
    LOCK,
    LOCKS,
    LODGE,
    LOOP,
    MALL,
    MANOR,
    MANORS,
    MEADOW,
    MEADOWS,
    MEWS,
    MILL,
    MILLS,
    MISSION,
    MOTORWAY,
    MOUNT,
    MOUNTAIN,
    MOUNTAINS,
    NECK,
    ORCHARD,
    OVAL,
    OVERPASS,
    PARK,
    PARKWAY,
    PASS,
    PASSAGE,
    PATH,
    PIKE,
    PINE,
    PINES,
    PLACE,
    PLAIN,
    PLAINS,
    PLAZA,
    POINT,
    POINTS,
    PORT,
    PORTS,
    PRAIRIE,
    RADIAL,
    RAMP,
    RANCH,
    RAPID,
    RAPIDS,
    REST,
    RIDGE,
    RIDGES,
    RIVER,
    ROAD,
    ROADS,
    ROUTE,
    ROW,
    RUE,
    RUN,
    SHOAL,
    SHOALS,
    SHORE,
    SHORES,
    SKYWAY,
    SPRING,
    SPRINGS,
    SPUR,
    SQUARE,
    SQUARES,
    STATION,
    STRAVENUE,
    STREAM,
    #[default]
    STREET,
    STREETS,
    SUMMIT,
    TERRACE,
    THROUGHWAY,
    TRACE,
    TRACK,
    TRAFFICWAY,
    TRAIL,
    TRAILER,
    TUNNEL,
    TURNPIKE,
    UNDERPASS,
    UNION,
    UNIONS,
    VALLEY,
    VALLEYS,
    VIADUCT,
    VIEW,
    VIEWS,
    VILLAGE,
    VILLAGES,
    VILLE,
    VISTA,
    WALK,
    WALL,
    WAY,
    WAYS,
    WELL,
    WELLS,
}

pub fn deserialize_abbreviated_post_type<'de, D: Deserializer<'de>>(
    de: D,
) -> Result<Option<StreetNamePostType>, D::Error> {
    let intermediate = Deserialize::deserialize(de)?;

    match intermediate {
        "ALY" => Ok(Some(StreetNamePostType::ALLEY)),
        "ANX" => Ok(Some(StreetNamePostType::ANEX)),
        "ARC" => Ok(Some(StreetNamePostType::ARCADE)),
        "AVE" => Ok(Some(StreetNamePostType::AVENUE)),
        "BYU" => Ok(Some(StreetNamePostType::BAYOU)),
        "BCH" => Ok(Some(StreetNamePostType::BEACH)),
        "BND" => Ok(Some(StreetNamePostType::BEND)),
        "BLF" => Ok(Some(StreetNamePostType::BLUFF)),
        "BLFS" => Ok(Some(StreetNamePostType::BLUFFS)),
        "BTM" => Ok(Some(StreetNamePostType::BOTTOM)),
        "BLVD" => Ok(Some(StreetNamePostType::BOULEVARD)),
        "BR" => Ok(Some(StreetNamePostType::BRANCH)),
        "BRG" => Ok(Some(StreetNamePostType::BRIDGE)),
        "BRK" => Ok(Some(StreetNamePostType::BROOK)),
        "BRKS" => Ok(Some(StreetNamePostType::BROOKS)),
        "BG" => Ok(Some(StreetNamePostType::BURG)),
        "BGS" => Ok(Some(StreetNamePostType::BURGS)),
        "BYP" => Ok(Some(StreetNamePostType::BYPASS)),
        "CP" => Ok(Some(StreetNamePostType::CAMP)),
        "CYN" => Ok(Some(StreetNamePostType::CANYON)),
        "CPE" => Ok(Some(StreetNamePostType::CAPE)),
        "CSWY" => Ok(Some(StreetNamePostType::CAUSEWAY)),
        "CTR" => Ok(Some(StreetNamePostType::CENTER)),
        "CTRS" => Ok(Some(StreetNamePostType::CENTERS)),
        "CIR" => Ok(Some(StreetNamePostType::CIRCLE)),
        "CIRS" => Ok(Some(StreetNamePostType::CIRCLES)),
        "CLF" => Ok(Some(StreetNamePostType::CLIFF)),
        "CLFS" => Ok(Some(StreetNamePostType::CLIFFS)),
        "CLB" => Ok(Some(StreetNamePostType::CLUB)),
        "CMN" => Ok(Some(StreetNamePostType::COMMON)),
        "CMNS" => Ok(Some(StreetNamePostType::COMMONS)),
        "COR" => Ok(Some(StreetNamePostType::CORNER)),
        "CORS" => Ok(Some(StreetNamePostType::CORNERS)),
        "CRSE" => Ok(Some(StreetNamePostType::COURSE)),
        "CT" => Ok(Some(StreetNamePostType::COURT)),
        "CTS" => Ok(Some(StreetNamePostType::COURTS)),
        "CV" => Ok(Some(StreetNamePostType::COVE)),
        "CVS" => Ok(Some(StreetNamePostType::COVES)),
        "CRK" => Ok(Some(StreetNamePostType::CREEK)),
        "CRES" => Ok(Some(StreetNamePostType::CRESCENT)),
        "CRST" => Ok(Some(StreetNamePostType::CREST)),
        "XING" => Ok(Some(StreetNamePostType::CROSSING)),
        "XRD" => Ok(Some(StreetNamePostType::CROSSROAD)),
        "XRDS" => Ok(Some(StreetNamePostType::CROSSROADS)),
        "CURV" => Ok(Some(StreetNamePostType::CURVE)),
        "CUTOFF" => Ok(Some(StreetNamePostType::CUTOFF)),
        "DL" => Ok(Some(StreetNamePostType::DALE)),
        "DM" => Ok(Some(StreetNamePostType::DAM)),
        "DV" => Ok(Some(StreetNamePostType::DIVIDE)),
        "DR" => Ok(Some(StreetNamePostType::DRIVE)),
        "DR CUTOFF" => Ok(Some(StreetNamePostType::DriveCutoff)),
        "DRS" => Ok(Some(StreetNamePostType::DRIVES)),
        "EST" => Ok(Some(StreetNamePostType::ESTATE)),
        "ESTS" => Ok(Some(StreetNamePostType::ESTATES)),
        "EXPY" => Ok(Some(StreetNamePostType::EXPRESSWAY)),
        "EXT" => Ok(Some(StreetNamePostType::EXTENSION)),
        "EXTS" => Ok(Some(StreetNamePostType::EXTENSIONS)),
        "FALL" => Ok(Some(StreetNamePostType::FALL)),
        "FLS" => Ok(Some(StreetNamePostType::FALLS)),
        "FRY" => Ok(Some(StreetNamePostType::FERRY)),
        "FLD" => Ok(Some(StreetNamePostType::FIELD)),
        "FLDS" => Ok(Some(StreetNamePostType::FIELDS)),
        "FLT" => Ok(Some(StreetNamePostType::FLAT)),
        "FLTS" => Ok(Some(StreetNamePostType::FLATS)),
        "FRD" => Ok(Some(StreetNamePostType::FORD)),
        "FRDS" => Ok(Some(StreetNamePostType::FORDS)),
        "FRST" => Ok(Some(StreetNamePostType::FOREST)),
        "FRG" => Ok(Some(StreetNamePostType::FORGE)),
        "FRGS" => Ok(Some(StreetNamePostType::FORGES)),
        "FRK" => Ok(Some(StreetNamePostType::FORK)),
        "FRKS" => Ok(Some(StreetNamePostType::FORKS)),
        "FT" => Ok(Some(StreetNamePostType::FORT)),
        "FWY" => Ok(Some(StreetNamePostType::FREEWAY)),
        "GDN" => Ok(Some(StreetNamePostType::GARDEN)),
        "GDNS" => Ok(Some(StreetNamePostType::GARDENS)),
        "GTWY" => Ok(Some(StreetNamePostType::GATEWAY)),
        "GLN" => Ok(Some(StreetNamePostType::GLEN)),
        "GLNS" => Ok(Some(StreetNamePostType::GLENS)),
        "GRN" => Ok(Some(StreetNamePostType::GREEN)),
        "GRNS" => Ok(Some(StreetNamePostType::GREENS)),
        "GRV" => Ok(Some(StreetNamePostType::GROVE)),
        "GRVS" => Ok(Some(StreetNamePostType::GROVES)),
        "HBR" => Ok(Some(StreetNamePostType::HARBOR)),
        "HBRS" => Ok(Some(StreetNamePostType::HARBORS)),
        "HVN" => Ok(Some(StreetNamePostType::HAVEN)),
        "HTS" => Ok(Some(StreetNamePostType::HEIGHTS)),
        "HWY" => Ok(Some(StreetNamePostType::HIGHWAY)),
        "HL" => Ok(Some(StreetNamePostType::HILL)),
        "HLS" => Ok(Some(StreetNamePostType::HILLS)),
        "HOLW" => Ok(Some(StreetNamePostType::HOLLOW)),
        "INLT" => Ok(Some(StreetNamePostType::INLET)),
        "IS" => Ok(Some(StreetNamePostType::ISLAND)),
        "ISS" => Ok(Some(StreetNamePostType::ISLANDS)),
        "ISLE" => Ok(Some(StreetNamePostType::ISLE)),
        "JCT" => Ok(Some(StreetNamePostType::JUNCTION)),
        "JCTS" => Ok(Some(StreetNamePostType::JUNCTIONS)),
        "KY" => Ok(Some(StreetNamePostType::KEY)),
        "KYS" => Ok(Some(StreetNamePostType::KEYS)),
        "KNL" => Ok(Some(StreetNamePostType::KNOLL)),
        "KNLS" => Ok(Some(StreetNamePostType::KNOLLS)),
        "LK" => Ok(Some(StreetNamePostType::LAKE)),
        "LKS" => Ok(Some(StreetNamePostType::LAKES)),
        "LAND" => Ok(Some(StreetNamePostType::LAND)),
        "LNDG" => Ok(Some(StreetNamePostType::LANDING)),
        "LN" => Ok(Some(StreetNamePostType::LANE)),
        "LGT" => Ok(Some(StreetNamePostType::LIGHT)),
        "LGTS" => Ok(Some(StreetNamePostType::LIGHTS)),
        "LF" => Ok(Some(StreetNamePostType::LOAF)),
        "LCK" => Ok(Some(StreetNamePostType::LOCK)),
        "LCKS" => Ok(Some(StreetNamePostType::LOCKS)),
        "LDG" => Ok(Some(StreetNamePostType::LODGE)),
        "LOOP" => Ok(Some(StreetNamePostType::LOOP)),
        "MALL" => Ok(Some(StreetNamePostType::MALL)),
        "MNR" => Ok(Some(StreetNamePostType::MANOR)),
        "MNRS" => Ok(Some(StreetNamePostType::MANORS)),
        "MDW" => Ok(Some(StreetNamePostType::MEADOW)),
        "MDWS" => Ok(Some(StreetNamePostType::MEADOWS)),
        "MEWS" => Ok(Some(StreetNamePostType::MEWS)),
        "ML" => Ok(Some(StreetNamePostType::MILL)),
        "MLS" => Ok(Some(StreetNamePostType::MILLS)),
        "MSN" => Ok(Some(StreetNamePostType::MISSION)),
        "MTWY" => Ok(Some(StreetNamePostType::MOTORWAY)),
        "MT" => Ok(Some(StreetNamePostType::MOUNT)),
        "MTN" => Ok(Some(StreetNamePostType::MOUNTAIN)),
        "MTNS" => Ok(Some(StreetNamePostType::MOUNTAINS)),
        "NCK" => Ok(Some(StreetNamePostType::NECK)),
        "ORCH" => Ok(Some(StreetNamePostType::ORCHARD)),
        "OVAL" => Ok(Some(StreetNamePostType::OVAL)),
        "OPAS" => Ok(Some(StreetNamePostType::OVERPASS)),
        "PARK" => Ok(Some(StreetNamePostType::PARK)),
        "PKWY" => Ok(Some(StreetNamePostType::PARKWAY)),
        "PASS" => Ok(Some(StreetNamePostType::PASS)),
        "PSGE" => Ok(Some(StreetNamePostType::PASSAGE)),
        "PATH" => Ok(Some(StreetNamePostType::PATH)),
        "PIKE" => Ok(Some(StreetNamePostType::PIKE)),
        "PNE" => Ok(Some(StreetNamePostType::PINE)),
        "PNES" => Ok(Some(StreetNamePostType::PINES)),
        "PL" => Ok(Some(StreetNamePostType::PLACE)),
        "PLN" => Ok(Some(StreetNamePostType::PLAIN)),
        "PLNS" => Ok(Some(StreetNamePostType::PLAINS)),
        "PLZ" => Ok(Some(StreetNamePostType::PLAZA)),
        "PT" => Ok(Some(StreetNamePostType::POINT)),
        "PTS" => Ok(Some(StreetNamePostType::POINTS)),
        "PRT" => Ok(Some(StreetNamePostType::PORT)),
        "PRTS" => Ok(Some(StreetNamePostType::PORTS)),
        "PR" => Ok(Some(StreetNamePostType::PRAIRIE)),
        "RADL" => Ok(Some(StreetNamePostType::RADIAL)),
        "RAMP" => Ok(Some(StreetNamePostType::RAMP)),
        "RNCH" => Ok(Some(StreetNamePostType::RANCH)),
        "RPD" => Ok(Some(StreetNamePostType::RAPID)),
        "RPDS" => Ok(Some(StreetNamePostType::RAPIDS)),
        "RST" => Ok(Some(StreetNamePostType::REST)),
        "RDG" => Ok(Some(StreetNamePostType::RIDGE)),
        "RDGS" => Ok(Some(StreetNamePostType::RIDGES)),
        "RIV" => Ok(Some(StreetNamePostType::RIVER)),
        "RD" => Ok(Some(StreetNamePostType::ROAD)),
        "RDS" => Ok(Some(StreetNamePostType::ROADS)),
        "RTE" => Ok(Some(StreetNamePostType::ROUTE)),
        "ROW" => Ok(Some(StreetNamePostType::ROW)),
        "RUE" => Ok(Some(StreetNamePostType::RUE)),
        "RUN" => Ok(Some(StreetNamePostType::RUN)),
        "SHL" => Ok(Some(StreetNamePostType::SHOAL)),
        "SHLS" => Ok(Some(StreetNamePostType::SHOALS)),
        "SHR" => Ok(Some(StreetNamePostType::SHORE)),
        "SHRS" => Ok(Some(StreetNamePostType::SHORES)),
        "SKWY" => Ok(Some(StreetNamePostType::SKYWAY)),
        "SPG" => Ok(Some(StreetNamePostType::SPRING)),
        "SPGS" => Ok(Some(StreetNamePostType::SPRINGS)),
        "SPUR" => Ok(Some(StreetNamePostType::SPUR)),
        "SQ" => Ok(Some(StreetNamePostType::SQUARE)),
        "SQS" => Ok(Some(StreetNamePostType::SQUARES)),
        "STA" => Ok(Some(StreetNamePostType::STATION)),
        "STRA" => Ok(Some(StreetNamePostType::STRAVENUE)),
        "STRM" => Ok(Some(StreetNamePostType::STREAM)),
        "ST" => Ok(Some(StreetNamePostType::STREET)),
        "STS" => Ok(Some(StreetNamePostType::STREETS)),
        "SMT" => Ok(Some(StreetNamePostType::SUMMIT)),
        "TER" => Ok(Some(StreetNamePostType::TERRACE)),
        "TRWY" => Ok(Some(StreetNamePostType::THROUGHWAY)),
        "TRCE" => Ok(Some(StreetNamePostType::TRACE)),
        "TRAK" => Ok(Some(StreetNamePostType::TRACK)),
        "TRFY" => Ok(Some(StreetNamePostType::TRAFFICWAY)),
        "TRL" => Ok(Some(StreetNamePostType::TRAIL)),
        "TRLR" => Ok(Some(StreetNamePostType::TRAILER)),
        "TUNL" => Ok(Some(StreetNamePostType::TUNNEL)),
        "TPKE" => Ok(Some(StreetNamePostType::TURNPIKE)),
        "UPAS" => Ok(Some(StreetNamePostType::UNDERPASS)),
        "UN" => Ok(Some(StreetNamePostType::UNION)),
        "UNS" => Ok(Some(StreetNamePostType::UNIONS)),
        "VLY" => Ok(Some(StreetNamePostType::VALLEY)),
        "VLYS" => Ok(Some(StreetNamePostType::VALLEYS)),
        "VIA" => Ok(Some(StreetNamePostType::VIADUCT)),
        "VW" => Ok(Some(StreetNamePostType::VIEW)),
        "VWS" => Ok(Some(StreetNamePostType::VIEWS)),
        "VLG" => Ok(Some(StreetNamePostType::VILLAGE)),
        "VLGS" => Ok(Some(StreetNamePostType::VILLAGES)),
        "VL" => Ok(Some(StreetNamePostType::VILLE)),
        "VIS" => Ok(Some(StreetNamePostType::VISTA)),
        "WALK" => Ok(Some(StreetNamePostType::WALK)),
        "WALL" => Ok(Some(StreetNamePostType::WALL)),
        "WAY" => Ok(Some(StreetNamePostType::WAY)),
        "WAYS" => Ok(Some(StreetNamePostType::WAYS)),
        "WL" => Ok(Some(StreetNamePostType::WELL)),
        "WLS" => Ok(Some(StreetNamePostType::WELLS)),
        _ => Ok(None),
    }
}

pub fn deserialize_mixed_post_type<'de, D: Deserializer<'de>>(
    de: D,
) -> Result<Option<StreetNamePostType>, D::Error> {
    let intermediate = Deserialize::deserialize(de)?;
    let result = match_mixed_post_type(intermediate);
    Ok(result)
}

//     match intermediate {
//         "ALY" => Ok(Some(StreetNamePostType::ALLEY)),
//         "ANX" => Ok(Some(StreetNamePostType::ANEX)),
//         "ARC" => Ok(Some(StreetNamePostType::ARCADE)),
//         "AVE" => Ok(Some(StreetNamePostType::AVENUE)),
//         "Ave" => Ok(Some(StreetNamePostType::AVENUE)),
//         "AVENUE" => Ok(Some(StreetNamePostType::AVENUE)),
//         "BYU" => Ok(Some(StreetNamePostType::BAYOU)),
//         "BCH" => Ok(Some(StreetNamePostType::BEACH)),
//         "BND" => Ok(Some(StreetNamePostType::BEND)),
//         "BLF" => Ok(Some(StreetNamePostType::BLUFF)),
//         "BLFS" => Ok(Some(StreetNamePostType::BLUFFS)),
//         "BTM" => Ok(Some(StreetNamePostType::BOTTOM)),
//         "BLVD" => Ok(Some(StreetNamePostType::BOULEVARD)),
//         "Blvd" => Ok(Some(StreetNamePostType::BOULEVARD)),
//         "BOULEVARD" => Ok(Some(StreetNamePostType::BOULEVARD)),
//         "BR" => Ok(Some(StreetNamePostType::BRANCH)),
//         "BRG" => Ok(Some(StreetNamePostType::BRIDGE)),
//         "BRK" => Ok(Some(StreetNamePostType::BROOK)),
//         "BRKS" => Ok(Some(StreetNamePostType::BROOKS)),
//         "BG" => Ok(Some(StreetNamePostType::BURG)),
//         "BGS" => Ok(Some(StreetNamePostType::BURGS)),
//         "BYP" => Ok(Some(StreetNamePostType::BYPASS)),
//         "CP" => Ok(Some(StreetNamePostType::CAMP)),
//         "CYN" => Ok(Some(StreetNamePostType::CANYON)),
//         "CPE" => Ok(Some(StreetNamePostType::CAPE)),
//         "CSWY" => Ok(Some(StreetNamePostType::CAUSEWAY)),
//         "CTR" => Ok(Some(StreetNamePostType::CENTER)),
//         "CTRS" => Ok(Some(StreetNamePostType::CENTERS)),
//         "CIR" => Ok(Some(StreetNamePostType::CIRCLE)),
//         "CIRCLE" => Ok(Some(StreetNamePostType::CIRCLE)),
//         "Circle" => Ok(Some(StreetNamePostType::CIRCLE)),
//         "CIRS" => Ok(Some(StreetNamePostType::CIRCLES)),
//         "CLF" => Ok(Some(StreetNamePostType::CLIFF)),
//         "CLFS" => Ok(Some(StreetNamePostType::CLIFFS)),
//         "CLB" => Ok(Some(StreetNamePostType::CLUB)),
//         "CMN" => Ok(Some(StreetNamePostType::COMMON)),
//         "CMNS" => Ok(Some(StreetNamePostType::COMMONS)),
//         "COR" => Ok(Some(StreetNamePostType::CORNER)),
//         "CORS" => Ok(Some(StreetNamePostType::CORNERS)),
//         "CRSE" => Ok(Some(StreetNamePostType::COURSE)),
//         "CT" => Ok(Some(StreetNamePostType::COURT)),
//         "Ct" => Ok(Some(StreetNamePostType::COURT)),
//         "CTS" => Ok(Some(StreetNamePostType::COURTS)),
//         "CV" => Ok(Some(StreetNamePostType::COVE)),
//         "CVS" => Ok(Some(StreetNamePostType::COVES)),
//         "CRK" => Ok(Some(StreetNamePostType::CREEK)),
//         "CRES" => Ok(Some(StreetNamePostType::CRESCENT)),
//         "CRST" => Ok(Some(StreetNamePostType::CREST)),
//         "CREST" => Ok(Some(StreetNamePostType::CREST)),
//         "XING" => Ok(Some(StreetNamePostType::CROSSING)),
//         "XRD" => Ok(Some(StreetNamePostType::CROSSROAD)),
//         "XRDS" => Ok(Some(StreetNamePostType::CROSSROADS)),
//         "CURV" => Ok(Some(StreetNamePostType::CURVE)),
//         "CUTOFF" => Ok(Some(StreetNamePostType::CUTOFF)),
//         "DL" => Ok(Some(StreetNamePostType::DALE)),
//         "DM" => Ok(Some(StreetNamePostType::DAM)),
//         "DV" => Ok(Some(StreetNamePostType::DIVIDE)),
//         "DR" => Ok(Some(StreetNamePostType::DRIVE)),
//         "Dr" => Ok(Some(StreetNamePostType::DRIVE)),
//         "DR CUTOFF" => Ok(Some(StreetNamePostType::DriveCutoff)),
//         "DRS" => Ok(Some(StreetNamePostType::DRIVES)),
//         "EST" => Ok(Some(StreetNamePostType::ESTATE)),
//         "ESTS" => Ok(Some(StreetNamePostType::ESTATES)),
//         "EXPY" => Ok(Some(StreetNamePostType::EXPRESSWAY)),
//         "EXT" => Ok(Some(StreetNamePostType::EXTENSION)),
//         "EXTS" => Ok(Some(StreetNamePostType::EXTENSIONS)),
//         "FALL" => Ok(Some(StreetNamePostType::FALL)),
//         "FLS" => Ok(Some(StreetNamePostType::FALLS)),
//         "FRY" => Ok(Some(StreetNamePostType::FERRY)),
//         "FLD" => Ok(Some(StreetNamePostType::FIELD)),
//         "FLDS" => Ok(Some(StreetNamePostType::FIELDS)),
//         "FLT" => Ok(Some(StreetNamePostType::FLAT)),
//         "FLTS" => Ok(Some(StreetNamePostType::FLATS)),
//         "FRD" => Ok(Some(StreetNamePostType::FORD)),
//         "FRDS" => Ok(Some(StreetNamePostType::FORDS)),
//         "FRST" => Ok(Some(StreetNamePostType::FOREST)),
//         "FRG" => Ok(Some(StreetNamePostType::FORGE)),
//         "FRGS" => Ok(Some(StreetNamePostType::FORGES)),
//         "FRK" => Ok(Some(StreetNamePostType::FORK)),
//         "FRKS" => Ok(Some(StreetNamePostType::FORKS)),
//         "FT" => Ok(Some(StreetNamePostType::FORT)),
//         "FWY" => Ok(Some(StreetNamePostType::FREEWAY)),
//         "GDN" => Ok(Some(StreetNamePostType::GARDEN)),
//         "GDNS" => Ok(Some(StreetNamePostType::GARDENS)),
//         "GTWY" => Ok(Some(StreetNamePostType::GATEWAY)),
//         "GLN" => Ok(Some(StreetNamePostType::GLEN)),
//         "GLNS" => Ok(Some(StreetNamePostType::GLENS)),
//         "GRN" => Ok(Some(StreetNamePostType::GREEN)),
//         "GRNS" => Ok(Some(StreetNamePostType::GREENS)),
//         "GRV" => Ok(Some(StreetNamePostType::GROVE)),
//         "GRVS" => Ok(Some(StreetNamePostType::GROVES)),
//         "HBR" => Ok(Some(StreetNamePostType::HARBOR)),
//         "HBRS" => Ok(Some(StreetNamePostType::HARBORS)),
//         "HVN" => Ok(Some(StreetNamePostType::HAVEN)),
//         "HTS" => Ok(Some(StreetNamePostType::HEIGHTS)),
//         "HWY" => Ok(Some(StreetNamePostType::HIGHWAY)),
//         "Hwy" => Ok(Some(StreetNamePostType::HIGHWAY)),
//         "HIGHWAY" => Ok(Some(StreetNamePostType::HIGHWAY)),
//         "HL" => Ok(Some(StreetNamePostType::HILL)),
//         "HLS" => Ok(Some(StreetNamePostType::HILLS)),
//         "HOLW" => Ok(Some(StreetNamePostType::HOLLOW)),
//         "INLT" => Ok(Some(StreetNamePostType::INLET)),
//         "IS" => Ok(Some(StreetNamePostType::ISLAND)),
//         "ISS" => Ok(Some(StreetNamePostType::ISLANDS)),
//         "ISLE" => Ok(Some(StreetNamePostType::ISLE)),
//         "JCT" => Ok(Some(StreetNamePostType::JUNCTION)),
//         "JCTS" => Ok(Some(StreetNamePostType::JUNCTIONS)),
//         "KY" => Ok(Some(StreetNamePostType::KEY)),
//         "KYS" => Ok(Some(StreetNamePostType::KEYS)),
//         "KNL" => Ok(Some(StreetNamePostType::KNOLL)),
//         "KNLS" => Ok(Some(StreetNamePostType::KNOLLS)),
//         "LK" => Ok(Some(StreetNamePostType::LAKE)),
//         "LKS" => Ok(Some(StreetNamePostType::LAKES)),
//         "LAND" => Ok(Some(StreetNamePostType::LAND)),
//         "LNDG" => Ok(Some(StreetNamePostType::LANDING)),
//         "LN" => Ok(Some(StreetNamePostType::LANE)),
//         "Ln" => Ok(Some(StreetNamePostType::LANE)),
//         "LANE" => Ok(Some(StreetNamePostType::LANE)),
//         "LGT" => Ok(Some(StreetNamePostType::LIGHT)),
//         "LGTS" => Ok(Some(StreetNamePostType::LIGHTS)),
//         "LF" => Ok(Some(StreetNamePostType::LOAF)),
//         "LCK" => Ok(Some(StreetNamePostType::LOCK)),
//         "LCKS" => Ok(Some(StreetNamePostType::LOCKS)),
//         "LDG" => Ok(Some(StreetNamePostType::LODGE)),
//         "LOOP" => Ok(Some(StreetNamePostType::LOOP)),
//         "MALL" => Ok(Some(StreetNamePostType::MALL)),
//         "MNR" => Ok(Some(StreetNamePostType::MANOR)),
//         "MNRS" => Ok(Some(StreetNamePostType::MANORS)),
//         "MDW" => Ok(Some(StreetNamePostType::MEADOW)),
//         "MDWS" => Ok(Some(StreetNamePostType::MEADOWS)),
//         "MEWS" => Ok(Some(StreetNamePostType::MEWS)),
//         "ML" => Ok(Some(StreetNamePostType::MILL)),
//         "MLS" => Ok(Some(StreetNamePostType::MILLS)),
//         "MSN" => Ok(Some(StreetNamePostType::MISSION)),
//         "MTWY" => Ok(Some(StreetNamePostType::MOTORWAY)),
//         "MT" => Ok(Some(StreetNamePostType::MOUNT)),
//         "MTN" => Ok(Some(StreetNamePostType::MOUNTAIN)),
//         "MTNS" => Ok(Some(StreetNamePostType::MOUNTAINS)),
//         "NCK" => Ok(Some(StreetNamePostType::NECK)),
//         "ORCH" => Ok(Some(StreetNamePostType::ORCHARD)),
//         "OVAL" => Ok(Some(StreetNamePostType::OVAL)),
//         "OPAS" => Ok(Some(StreetNamePostType::OVERPASS)),
//         "PARK" => Ok(Some(StreetNamePostType::PARK)),
//         "PKWY" => Ok(Some(StreetNamePostType::PARKWAY)),
//         "Pkwy" => Ok(Some(StreetNamePostType::PARKWAY)),
//         "PASS" => Ok(Some(StreetNamePostType::PASS)),
//         "PSGE" => Ok(Some(StreetNamePostType::PASSAGE)),
//         "PATH" => Ok(Some(StreetNamePostType::PATH)),
//         "PIKE" => Ok(Some(StreetNamePostType::PIKE)),
//         "PNE" => Ok(Some(StreetNamePostType::PINE)),
//         "PNES" => Ok(Some(StreetNamePostType::PINES)),
//         "PL" => Ok(Some(StreetNamePostType::PLACE)),
//         "PLN" => Ok(Some(StreetNamePostType::PLAIN)),
//         "PLNS" => Ok(Some(StreetNamePostType::PLAINS)),
//         "PLZ" => Ok(Some(StreetNamePostType::PLAZA)),
//         "PT" => Ok(Some(StreetNamePostType::POINT)),
//         "PTS" => Ok(Some(StreetNamePostType::POINTS)),
//         "PRT" => Ok(Some(StreetNamePostType::PORT)),
//         "PRTS" => Ok(Some(StreetNamePostType::PORTS)),
//         "PR" => Ok(Some(StreetNamePostType::PRAIRIE)),
//         "RADL" => Ok(Some(StreetNamePostType::RADIAL)),
//         "RAMP" => Ok(Some(StreetNamePostType::RAMP)),
//         "RNCH" => Ok(Some(StreetNamePostType::RANCH)),
//         "RPD" => Ok(Some(StreetNamePostType::RAPID)),
//         "RPDS" => Ok(Some(StreetNamePostType::RAPIDS)),
//         "RST" => Ok(Some(StreetNamePostType::REST)),
//         "RDG" => Ok(Some(StreetNamePostType::RIDGE)),
//         "RDGS" => Ok(Some(StreetNamePostType::RIDGES)),
//         "RIV" => Ok(Some(StreetNamePostType::RIVER)),
//         "RD" => Ok(Some(StreetNamePostType::ROAD)),
//         "Rd" => Ok(Some(StreetNamePostType::ROAD)),
//         "RDS" => Ok(Some(StreetNamePostType::ROADS)),
//         "RTE" => Ok(Some(StreetNamePostType::ROUTE)),
//         "ROW" => Ok(Some(StreetNamePostType::ROW)),
//         "RUE" => Ok(Some(StreetNamePostType::RUE)),
//         "RUN" => Ok(Some(StreetNamePostType::RUN)),
//         "SHL" => Ok(Some(StreetNamePostType::SHOAL)),
//         "SHLS" => Ok(Some(StreetNamePostType::SHOALS)),
//         "SHR" => Ok(Some(StreetNamePostType::SHORE)),
//         "SHRS" => Ok(Some(StreetNamePostType::SHORES)),
//         "SKWY" => Ok(Some(StreetNamePostType::SKYWAY)),
//         "SPG" => Ok(Some(StreetNamePostType::SPRING)),
//         "SPGS" => Ok(Some(StreetNamePostType::SPRINGS)),
//         "SPUR" => Ok(Some(StreetNamePostType::SPUR)),
//         "SQ" => Ok(Some(StreetNamePostType::SQUARE)),
//         "SQS" => Ok(Some(StreetNamePostType::SQUARES)),
//         "STA" => Ok(Some(StreetNamePostType::STATION)),
//         "STRA" => Ok(Some(StreetNamePostType::STRAVENUE)),
//         "STRM" => Ok(Some(StreetNamePostType::STREAM)),
//         "ST" => Ok(Some(StreetNamePostType::STREET)),
//         "St" => Ok(Some(StreetNamePostType::STREET)),
//         "STREET" => Ok(Some(StreetNamePostType::STREET)),
//         "STS" => Ok(Some(StreetNamePostType::STREETS)),
//         "SMT" => Ok(Some(StreetNamePostType::SUMMIT)),
//         "TER" => Ok(Some(StreetNamePostType::TERRACE)),
//         "TRWY" => Ok(Some(StreetNamePostType::THROUGHWAY)),
//         "TRCE" => Ok(Some(StreetNamePostType::TRACE)),
//         "TRAK" => Ok(Some(StreetNamePostType::TRACK)),
//         "TRFY" => Ok(Some(StreetNamePostType::TRAFFICWAY)),
//         "TRL" => Ok(Some(StreetNamePostType::TRAIL)),
//         "TRLR" => Ok(Some(StreetNamePostType::TRAILER)),
//         "TUNL" => Ok(Some(StreetNamePostType::TUNNEL)),
//         "TPKE" => Ok(Some(StreetNamePostType::TURNPIKE)),
//         "UPAS" => Ok(Some(StreetNamePostType::UNDERPASS)),
//         "UN" => Ok(Some(StreetNamePostType::UNION)),
//         "UNS" => Ok(Some(StreetNamePostType::UNIONS)),
//         "VLY" => Ok(Some(StreetNamePostType::VALLEY)),
//         "VLYS" => Ok(Some(StreetNamePostType::VALLEYS)),
//         "VIA" => Ok(Some(StreetNamePostType::VIADUCT)),
//         "VW" => Ok(Some(StreetNamePostType::VIEW)),
//         "VWS" => Ok(Some(StreetNamePostType::VIEWS)),
//         "VLG" => Ok(Some(StreetNamePostType::VILLAGE)),
//         "VLGS" => Ok(Some(StreetNamePostType::VILLAGES)),
//         "VL" => Ok(Some(StreetNamePostType::VILLE)),
//         "VIS" => Ok(Some(StreetNamePostType::VISTA)),
//         "WALK" => Ok(Some(StreetNamePostType::WALK)),
//         "WALL" => Ok(Some(StreetNamePostType::WALL)),
//         "WAY" => Ok(Some(StreetNamePostType::WAY)),
//         "Way" => Ok(Some(StreetNamePostType::WAY)),
//         "WAYS" => Ok(Some(StreetNamePostType::WAYS)),
//         "WL" => Ok(Some(StreetNamePostType::WELL)),
//         "WLS" => Ok(Some(StreetNamePostType::WELLS)),
//         _ => Ok(None),
//     }
// }

pub fn match_mixed_post_type(input: &str) -> Option<StreetNamePostType> {
    match input {
        "ALY" => Some(StreetNamePostType::ALLEY),
        "ANX" => Some(StreetNamePostType::ANEX),
        "ARC" => Some(StreetNamePostType::ARCADE),
        "AVE" => Some(StreetNamePostType::AVENUE),
        "Ave" => Some(StreetNamePostType::AVENUE),
        "AVENUE" => Some(StreetNamePostType::AVENUE),
        "BYU" => Some(StreetNamePostType::BAYOU),
        "BCH" => Some(StreetNamePostType::BEACH),
        "BND" => Some(StreetNamePostType::BEND),
        "BLF" => Some(StreetNamePostType::BLUFF),
        "BLFS" => Some(StreetNamePostType::BLUFFS),
        "BTM" => Some(StreetNamePostType::BOTTOM),
        "BLVD" => Some(StreetNamePostType::BOULEVARD),
        "Blvd" => Some(StreetNamePostType::BOULEVARD),
        "BOULEVARD" => Some(StreetNamePostType::BOULEVARD),
        "BR" => Some(StreetNamePostType::BRANCH),
        "BRG" => Some(StreetNamePostType::BRIDGE),
        "BRK" => Some(StreetNamePostType::BROOK),
        "BRKS" => Some(StreetNamePostType::BROOKS),
        "BG" => Some(StreetNamePostType::BURG),
        "BGS" => Some(StreetNamePostType::BURGS),
        "BYP" => Some(StreetNamePostType::BYPASS),
        "CP" => Some(StreetNamePostType::CAMP),
        "CYN" => Some(StreetNamePostType::CANYON),
        "CPE" => Some(StreetNamePostType::CAPE),
        "CSWY" => Some(StreetNamePostType::CAUSEWAY),
        "CTR" => Some(StreetNamePostType::CENTER),
        "CTRS" => Some(StreetNamePostType::CENTERS),
        "CIR" => Some(StreetNamePostType::CIRCLE),
        "CIRCLE" => Some(StreetNamePostType::CIRCLE),
        "Circle" => Some(StreetNamePostType::CIRCLE),
        "CIRS" => Some(StreetNamePostType::CIRCLES),
        "CLF" => Some(StreetNamePostType::CLIFF),
        "CLFS" => Some(StreetNamePostType::CLIFFS),
        "CLB" => Some(StreetNamePostType::CLUB),
        "CMN" => Some(StreetNamePostType::COMMON),
        "CMNS" => Some(StreetNamePostType::COMMONS),
        "COR" => Some(StreetNamePostType::CORNER),
        "CORS" => Some(StreetNamePostType::CORNERS),
        "CRSE" => Some(StreetNamePostType::COURSE),
        "CT" => Some(StreetNamePostType::COURT),
        "Ct" => Some(StreetNamePostType::COURT),
        "CTS" => Some(StreetNamePostType::COURTS),
        "CV" => Some(StreetNamePostType::COVE),
        "CVS" => Some(StreetNamePostType::COVES),
        "CRK" => Some(StreetNamePostType::CREEK),
        "CRES" => Some(StreetNamePostType::CRESCENT),
        "CRST" => Some(StreetNamePostType::CREST),
        "CREST" => Some(StreetNamePostType::CREST),
        "XING" => Some(StreetNamePostType::CROSSING),
        "XRD" => Some(StreetNamePostType::CROSSROAD),
        "XRDS" => Some(StreetNamePostType::CROSSROADS),
        "CURV" => Some(StreetNamePostType::CURVE),
        "CUTOFF" => Some(StreetNamePostType::CUTOFF),
        "DL" => Some(StreetNamePostType::DALE),
        "DM" => Some(StreetNamePostType::DAM),
        "DV" => Some(StreetNamePostType::DIVIDE),
        "DR" => Some(StreetNamePostType::DRIVE),
        "Dr" => Some(StreetNamePostType::DRIVE),
        "DR CUTOFF" => Some(StreetNamePostType::DriveCutoff),
        "DRS" => Some(StreetNamePostType::DRIVES),
        "EST" => Some(StreetNamePostType::ESTATE),
        "ESTS" => Some(StreetNamePostType::ESTATES),
        "EXPY" => Some(StreetNamePostType::EXPRESSWAY),
        "EXT" => Some(StreetNamePostType::EXTENSION),
        "EXTS" => Some(StreetNamePostType::EXTENSIONS),
        "FALL" => Some(StreetNamePostType::FALL),
        "FLS" => Some(StreetNamePostType::FALLS),
        "FRY" => Some(StreetNamePostType::FERRY),
        "FLD" => Some(StreetNamePostType::FIELD),
        "FLDS" => Some(StreetNamePostType::FIELDS),
        "FLT" => Some(StreetNamePostType::FLAT),
        "FLTS" => Some(StreetNamePostType::FLATS),
        "FRD" => Some(StreetNamePostType::FORD),
        "FRDS" => Some(StreetNamePostType::FORDS),
        "FRST" => Some(StreetNamePostType::FOREST),
        "FRG" => Some(StreetNamePostType::FORGE),
        "FRGS" => Some(StreetNamePostType::FORGES),
        "FRK" => Some(StreetNamePostType::FORK),
        "FRKS" => Some(StreetNamePostType::FORKS),
        "FT" => Some(StreetNamePostType::FORT),
        "FWY" => Some(StreetNamePostType::FREEWAY),
        "GDN" => Some(StreetNamePostType::GARDEN),
        "GARDEN" => Some(StreetNamePostType::GARDEN),
        "GDNS" => Some(StreetNamePostType::GARDENS),
        "GTWY" => Some(StreetNamePostType::GATEWAY),
        "GLN" => Some(StreetNamePostType::GLEN),
        "GLNS" => Some(StreetNamePostType::GLENS),
        "GRN" => Some(StreetNamePostType::GREEN),
        "GRNS" => Some(StreetNamePostType::GREENS),
        "GRV" => Some(StreetNamePostType::GROVE),
        "GRVS" => Some(StreetNamePostType::GROVES),
        "HBR" => Some(StreetNamePostType::HARBOR),
        "HBRS" => Some(StreetNamePostType::HARBORS),
        "HVN" => Some(StreetNamePostType::HAVEN),
        "HTS" => Some(StreetNamePostType::HEIGHTS),
        "HWY" => Some(StreetNamePostType::HIGHWAY),
        "Hwy" => Some(StreetNamePostType::HIGHWAY),
        "HIGHWAY" => Some(StreetNamePostType::HIGHWAY),
        "HL" => Some(StreetNamePostType::HILL),
        "HLS" => Some(StreetNamePostType::HILLS),
        "HOLW" => Some(StreetNamePostType::HOLLOW),
        "INLT" => Some(StreetNamePostType::INLET),
        "IS" => Some(StreetNamePostType::ISLAND),
        "ISS" => Some(StreetNamePostType::ISLANDS),
        "ISLE" => Some(StreetNamePostType::ISLE),
        "JCT" => Some(StreetNamePostType::JUNCTION),
        "JCTS" => Some(StreetNamePostType::JUNCTIONS),
        "KY" => Some(StreetNamePostType::KEY),
        "KYS" => Some(StreetNamePostType::KEYS),
        "KNL" => Some(StreetNamePostType::KNOLL),
        "KNLS" => Some(StreetNamePostType::KNOLLS),
        "LK" => Some(StreetNamePostType::LAKE),
        "LKS" => Some(StreetNamePostType::LAKES),
        "LAND" => Some(StreetNamePostType::LAND),
        "LNDG" => Some(StreetNamePostType::LANDING),
        "LN" => Some(StreetNamePostType::LANE),
        "Ln" => Some(StreetNamePostType::LANE),
        "LANE" => Some(StreetNamePostType::LANE),
        "LGT" => Some(StreetNamePostType::LIGHT),
        "LGTS" => Some(StreetNamePostType::LIGHTS),
        "LF" => Some(StreetNamePostType::LOAF),
        "LCK" => Some(StreetNamePostType::LOCK),
        "LCKS" => Some(StreetNamePostType::LOCKS),
        "LDG" => Some(StreetNamePostType::LODGE),
        "LOOP" => Some(StreetNamePostType::LOOP),
        "MALL" => Some(StreetNamePostType::MALL),
        "MNR" => Some(StreetNamePostType::MANOR),
        "MNRS" => Some(StreetNamePostType::MANORS),
        "MDW" => Some(StreetNamePostType::MEADOW),
        "MDWS" => Some(StreetNamePostType::MEADOWS),
        "MEWS" => Some(StreetNamePostType::MEWS),
        "ML" => Some(StreetNamePostType::MILL),
        "MLS" => Some(StreetNamePostType::MILLS),
        "MSN" => Some(StreetNamePostType::MISSION),
        "MTWY" => Some(StreetNamePostType::MOTORWAY),
        "MT" => Some(StreetNamePostType::MOUNT),
        "MTN" => Some(StreetNamePostType::MOUNTAIN),
        "MTNS" => Some(StreetNamePostType::MOUNTAINS),
        "NCK" => Some(StreetNamePostType::NECK),
        "ORCH" => Some(StreetNamePostType::ORCHARD),
        "OVAL" => Some(StreetNamePostType::OVAL),
        "OPAS" => Some(StreetNamePostType::OVERPASS),
        "PARK" => Some(StreetNamePostType::PARK),
        "PKWY" => Some(StreetNamePostType::PARKWAY),
        "Pkwy" => Some(StreetNamePostType::PARKWAY),
        "PASS" => Some(StreetNamePostType::PASS),
        "PSGE" => Some(StreetNamePostType::PASSAGE),
        "PATH" => Some(StreetNamePostType::PATH),
        "PIKE" => Some(StreetNamePostType::PIKE),
        "PNE" => Some(StreetNamePostType::PINE),
        "PNES" => Some(StreetNamePostType::PINES),
        "PL" => Some(StreetNamePostType::PLACE),
        "PLN" => Some(StreetNamePostType::PLAIN),
        "PLNS" => Some(StreetNamePostType::PLAINS),
        "PLZ" => Some(StreetNamePostType::PLAZA),
        "PT" => Some(StreetNamePostType::POINT),
        "PTS" => Some(StreetNamePostType::POINTS),
        "PRT" => Some(StreetNamePostType::PORT),
        "PRTS" => Some(StreetNamePostType::PORTS),
        "PR" => Some(StreetNamePostType::PRAIRIE),
        "RADL" => Some(StreetNamePostType::RADIAL),
        "RAMP" => Some(StreetNamePostType::RAMP),
        "RNCH" => Some(StreetNamePostType::RANCH),
        "RPD" => Some(StreetNamePostType::RAPID),
        "RPDS" => Some(StreetNamePostType::RAPIDS),
        "RST" => Some(StreetNamePostType::REST),
        "RDG" => Some(StreetNamePostType::RIDGE),
        "RDGS" => Some(StreetNamePostType::RIDGES),
        "RIV" => Some(StreetNamePostType::RIVER),
        "RD" => Some(StreetNamePostType::ROAD),
        "Rd" => Some(StreetNamePostType::ROAD),
        "RDS" => Some(StreetNamePostType::ROADS),
        "RTE" => Some(StreetNamePostType::ROUTE),
        "ROW" => Some(StreetNamePostType::ROW),
        "RUE" => Some(StreetNamePostType::RUE),
        "RUN" => Some(StreetNamePostType::RUN),
        "SHL" => Some(StreetNamePostType::SHOAL),
        "SHLS" => Some(StreetNamePostType::SHOALS),
        "SHR" => Some(StreetNamePostType::SHORE),
        "SHRS" => Some(StreetNamePostType::SHORES),
        "SKWY" => Some(StreetNamePostType::SKYWAY),
        "SPG" => Some(StreetNamePostType::SPRING),
        "SPGS" => Some(StreetNamePostType::SPRINGS),
        "SPUR" => Some(StreetNamePostType::SPUR),
        "SQ" => Some(StreetNamePostType::SQUARE),
        "SQS" => Some(StreetNamePostType::SQUARES),
        "STA" => Some(StreetNamePostType::STATION),
        "STRA" => Some(StreetNamePostType::STRAVENUE),
        "STRM" => Some(StreetNamePostType::STREAM),
        "ST" => Some(StreetNamePostType::STREET),
        "St" => Some(StreetNamePostType::STREET),
        "STREET" => Some(StreetNamePostType::STREET),
        "STS" => Some(StreetNamePostType::STREETS),
        "SMT" => Some(StreetNamePostType::SUMMIT),
        "TER" => Some(StreetNamePostType::TERRACE),
        "TRWY" => Some(StreetNamePostType::THROUGHWAY),
        "TRCE" => Some(StreetNamePostType::TRACE),
        "TRAK" => Some(StreetNamePostType::TRACK),
        "TRFY" => Some(StreetNamePostType::TRAFFICWAY),
        "TRL" => Some(StreetNamePostType::TRAIL),
        "TRLR" => Some(StreetNamePostType::TRAILER),
        "TUNL" => Some(StreetNamePostType::TUNNEL),
        "TPKE" => Some(StreetNamePostType::TURNPIKE),
        "UPAS" => Some(StreetNamePostType::UNDERPASS),
        "UN" => Some(StreetNamePostType::UNION),
        "UNS" => Some(StreetNamePostType::UNIONS),
        "VLY" => Some(StreetNamePostType::VALLEY),
        "VLYS" => Some(StreetNamePostType::VALLEYS),
        "VIA" => Some(StreetNamePostType::VIADUCT),
        "VW" => Some(StreetNamePostType::VIEW),
        "VIEW" => Some(StreetNamePostType::VIEW),
        "VWS" => Some(StreetNamePostType::VIEWS),
        "VLG" => Some(StreetNamePostType::VILLAGE),
        "VLGS" => Some(StreetNamePostType::VILLAGES),
        "VL" => Some(StreetNamePostType::VILLE),
        "VIS" => Some(StreetNamePostType::VISTA),
        "WALK" => Some(StreetNamePostType::WALK),
        "WALL" => Some(StreetNamePostType::WALL),
        "WAY" => Some(StreetNamePostType::WAY),
        "Way" => Some(StreetNamePostType::WAY),
        "WAYS" => Some(StreetNamePostType::WAYS),
        "WL" => Some(StreetNamePostType::WELL),
        "WLS" => Some(StreetNamePostType::WELLS),
        _ => None,
    }
}
