use serde::de::Deserializer;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
pub enum StreetNamePostType {
    ALLEY,
    ANEX,
    ARCADE,
    AVENUE,
    BAYOU,
    BEACH,
    BEND,
    BLUFF,
    BLUFFS,
    BOTTOM,
    BOULEVARD,
    BRANCH,
    BRIDGE,
    BROOK,
    BROOKS,
    BURG,
    BURGS,
    BYPASS,
    CAMP,
    CANYON,
    CAPE,
    CAUSEWAY,
    CENTER,
    CENTERS,
    CIRCLE,
    CIRCLES,
    CLIFF,
    CLIFFS,
    CLUB,
    COMMON,
    COMMONS,
    CORNER,
    CORNERS,
    COURSE,
    COURT,
    COURTS,
    COVE,
    COVES,
    CREEK,
    CRESCENT,
    CREST,
    CROSSING,
    CROSSROAD,
    CROSSROADS,
    CURVE,
    CUTOFF,
    DALE,
    DAM,
    DIVIDE,
    DRIVE,
    #[serde(rename(deserialize = "DRIVE CUTOFF"))]
    DriveCutoff,
    DRIVES,
    ESTATE,
    ESTATES,
    EXPRESSWAY,
    EXTENSION,
    EXTENSIONS,
    FALL,
    FALLS,
    FERRY,
    FIELD,
    FIELDS,
    FLAT,
    FLATS,
    FORD,
    FORDS,
    FOREST,
    FORGE,
    FORGES,
    FORK,
    FORKS,
    FORT,
    FREEWAY,
    GARDEN,
    GARDENS,
    GATEWAY,
    GLEN,
    GLENS,
    GREEN,
    GREENS,
    GROVE,
    GROVES,
    HARBOR,
    HARBORS,
    HAVEN,
    HEIGHTS,
    HIGHWAY,
    HILL,
    HILLS,
    HOLLOW,
    INLET,
    ISLAND,
    ISLANDS,
    ISLE,
    JUNCTION,
    JUNCTIONS,
    KEY,
    KEYS,
    KNOLL,
    KNOLLS,
    LAKE,
    LAKES,
    LAND,
    LANDING,
    LANE,
    LIGHT,
    LIGHTS,
    LOAF,
    LOCK,
    LOCKS,
    LODGE,
    LOOP,
    MALL,
    MANOR,
    MANORS,
    MEADOW,
    MEADOWS,
    MEWS,
    MILL,
    MILLS,
    MISSION,
    MOTORWAY,
    MOUNT,
    MOUNTAIN,
    MOUNTAINS,
    NECK,
    ORCHARD,
    OVAL,
    OVERPASS,
    PARK,
    PARKWAY,
    PASS,
    PASSAGE,
    PATH,
    PIKE,
    PINE,
    PINES,
    PLACE,
    PLAIN,
    PLAINS,
    PLAZA,
    POINT,
    POINTS,
    PORT,
    PORTS,
    PRAIRIE,
    RADIAL,
    RAMP,
    RANCH,
    RAPID,
    RAPIDS,
    REST,
    RIDGE,
    RIDGES,
    RIVER,
    ROAD,
    ROADS,
    ROUTE,
    ROW,
    RUE,
    RUN,
    SHOAL,
    SHOALS,
    SHORE,
    SHORES,
    SKYWAY,
    SPRING,
    SPRINGS,
    SPUR,
    SQUARE,
    SQUARES,
    STATION,
    STRAVENUE,
    STREAM,
    STREET,
    STREETS,
    SUMMIT,
    TERRACE,
    THROUGHWAY,
    TRACE,
    TRACK,
    TRAFFICWAY,
    TRAIL,
    TRAILER,
    TUNNEL,
    TURNPIKE,
    UNDERPASS,
    UNION,
    UNIONS,
    VALLEY,
    VALLEYS,
    VIADUCT,
    VIEW,
    VIEWS,
    VILLAGE,
    VILLAGES,
    VILLE,
    VISTA,
    WALK,
    WALL,
    WAY,
    WAYS,
    WELL,
    WELLS,
}

pub fn deserialize_abbreviated_post_type<'de, D: Deserializer<'de>>(
    de: D,
) -> Result<Option<StreetNamePostType>, D::Error> {
    let intermediate = Deserialize::deserialize(de)?;

    match intermediate {
        "ALY" => Ok(Some(StreetNamePostType::ALLEY)),
        "ANX" => Ok(Some(StreetNamePostType::ANEX)),
        "ARC" => Ok(Some(StreetNamePostType::ARCADE)),
        "AVE" => Ok(Some(StreetNamePostType::AVENUE)),
        "BYU" => Ok(Some(StreetNamePostType::BAYOU)),
        "BCH" => Ok(Some(StreetNamePostType::BEACH)),
        "BND" => Ok(Some(StreetNamePostType::BEND)),
        "BLF" => Ok(Some(StreetNamePostType::BLUFF)),
        "BLFS" => Ok(Some(StreetNamePostType::BLUFFS)),
        "BTM" => Ok(Some(StreetNamePostType::BOTTOM)),
        "BLVD" => Ok(Some(StreetNamePostType::BOULEVARD)),
        "BR" => Ok(Some(StreetNamePostType::BRANCH)),
        "BRG" => Ok(Some(StreetNamePostType::BRIDGE)),
        "BRK" => Ok(Some(StreetNamePostType::BROOK)),
        "BRKS" => Ok(Some(StreetNamePostType::BROOKS)),
        "BG" => Ok(Some(StreetNamePostType::BURG)),
        "BGS" => Ok(Some(StreetNamePostType::BURGS)),
        "BYP" => Ok(Some(StreetNamePostType::BYPASS)),
        "CP" => Ok(Some(StreetNamePostType::CAMP)),
        "CYN" => Ok(Some(StreetNamePostType::CANYON)),
        "CPE" => Ok(Some(StreetNamePostType::CAPE)),
        "CSWY" => Ok(Some(StreetNamePostType::CAUSEWAY)),
        "CTR" => Ok(Some(StreetNamePostType::CENTER)),
        "CTRS" => Ok(Some(StreetNamePostType::CENTERS)),
        "CIR" => Ok(Some(StreetNamePostType::CIRCLE)),
        "CIRS" => Ok(Some(StreetNamePostType::CIRCLES)),
        "CLF" => Ok(Some(StreetNamePostType::CLIFF)),
        "CLFS" => Ok(Some(StreetNamePostType::CLIFFS)),
        "CLB" => Ok(Some(StreetNamePostType::CLUB)),
        "CMN" => Ok(Some(StreetNamePostType::COMMON)),
        "CMNS" => Ok(Some(StreetNamePostType::COMMONS)),
        "COR" => Ok(Some(StreetNamePostType::CORNER)),
        "CORS" => Ok(Some(StreetNamePostType::CORNERS)),
        "CRSE" => Ok(Some(StreetNamePostType::COURSE)),
        "CT" => Ok(Some(StreetNamePostType::COURT)),
        "CTS" => Ok(Some(StreetNamePostType::COURTS)),
        "CV" => Ok(Some(StreetNamePostType::COVE)),
        "CVS" => Ok(Some(StreetNamePostType::COVES)),
        "CRK" => Ok(Some(StreetNamePostType::CREEK)),
        "CRES" => Ok(Some(StreetNamePostType::CRESCENT)),
        "CRST" => Ok(Some(StreetNamePostType::CREST)),
        "XING" => Ok(Some(StreetNamePostType::CROSSING)),
        "XRD" => Ok(Some(StreetNamePostType::CROSSROAD)),
        "XRDS" => Ok(Some(StreetNamePostType::CROSSROADS)),
        "CURV" => Ok(Some(StreetNamePostType::CURVE)),
        "CUTOFF" => Ok(Some(StreetNamePostType::CUTOFF)),
        "DL" => Ok(Some(StreetNamePostType::DALE)),
        "DM" => Ok(Some(StreetNamePostType::DAM)),
        "DV" => Ok(Some(StreetNamePostType::DIVIDE)),
        "DR" => Ok(Some(StreetNamePostType::DRIVE)),
        "DR CUTOFF" => Ok(Some(StreetNamePostType::DriveCutoff)),
        "DRS" => Ok(Some(StreetNamePostType::DRIVES)),
        "EST" => Ok(Some(StreetNamePostType::ESTATE)),
        "ESTS" => Ok(Some(StreetNamePostType::ESTATES)),
        "EXPY" => Ok(Some(StreetNamePostType::EXPRESSWAY)),
        "EXT" => Ok(Some(StreetNamePostType::EXTENSION)),
        "EXTS" => Ok(Some(StreetNamePostType::EXTENSIONS)),
        "FALL" => Ok(Some(StreetNamePostType::FALL)),
        "FLS" => Ok(Some(StreetNamePostType::FALLS)),
        "FRY" => Ok(Some(StreetNamePostType::FERRY)),
        "FLD" => Ok(Some(StreetNamePostType::FIELD)),
        "FLDS" => Ok(Some(StreetNamePostType::FIELDS)),
        "FLT" => Ok(Some(StreetNamePostType::FLAT)),
        "FLTS" => Ok(Some(StreetNamePostType::FLATS)),
        "FRD" => Ok(Some(StreetNamePostType::FORD)),
        "FRDS" => Ok(Some(StreetNamePostType::FORDS)),
        "FRST" => Ok(Some(StreetNamePostType::FOREST)),
        "FRG" => Ok(Some(StreetNamePostType::FORGE)),
        "FRGS" => Ok(Some(StreetNamePostType::FORGES)),
        "FRK" => Ok(Some(StreetNamePostType::FORK)),
        "FRKS" => Ok(Some(StreetNamePostType::FORKS)),
        "FT" => Ok(Some(StreetNamePostType::FORT)),
        "FWY" => Ok(Some(StreetNamePostType::FREEWAY)),
        "GDN" => Ok(Some(StreetNamePostType::GARDEN)),
        "GDNS" => Ok(Some(StreetNamePostType::GARDENS)),
        "GTWY" => Ok(Some(StreetNamePostType::GATEWAY)),
        "GLN" => Ok(Some(StreetNamePostType::GLEN)),
        "GLNS" => Ok(Some(StreetNamePostType::GLENS)),
        "GRN" => Ok(Some(StreetNamePostType::GREEN)),
        "GRNS" => Ok(Some(StreetNamePostType::GREENS)),
        "GRV" => Ok(Some(StreetNamePostType::GROVE)),
        "GRVS" => Ok(Some(StreetNamePostType::GROVES)),
        "HBR" => Ok(Some(StreetNamePostType::HARBOR)),
        "HBRS" => Ok(Some(StreetNamePostType::HARBORS)),
        "HVN" => Ok(Some(StreetNamePostType::HAVEN)),
        "HTS" => Ok(Some(StreetNamePostType::HEIGHTS)),
        "HWY" => Ok(Some(StreetNamePostType::HIGHWAY)),
        "HL" => Ok(Some(StreetNamePostType::HILL)),
        "HLS" => Ok(Some(StreetNamePostType::HILLS)),
        "HOLW" => Ok(Some(StreetNamePostType::HOLLOW)),
        "INLT" => Ok(Some(StreetNamePostType::INLET)),
        "IS" => Ok(Some(StreetNamePostType::ISLAND)),
        "ISS" => Ok(Some(StreetNamePostType::ISLANDS)),
        "ISLE" => Ok(Some(StreetNamePostType::ISLE)),
        "JCT" => Ok(Some(StreetNamePostType::JUNCTION)),
        "JCTS" => Ok(Some(StreetNamePostType::JUNCTIONS)),
        "KY" => Ok(Some(StreetNamePostType::KEY)),
        "KYS" => Ok(Some(StreetNamePostType::KEYS)),
        "KNL" => Ok(Some(StreetNamePostType::KNOLL)),
        "KNLS" => Ok(Some(StreetNamePostType::KNOLLS)),
        "LK" => Ok(Some(StreetNamePostType::LAKE)),
        "LKS" => Ok(Some(StreetNamePostType::LAKES)),
        "LAND" => Ok(Some(StreetNamePostType::LAND)),
        "LNDG" => Ok(Some(StreetNamePostType::LANDING)),
        "LN" => Ok(Some(StreetNamePostType::LANE)),
        "LGT" => Ok(Some(StreetNamePostType::LIGHT)),
        "LGTS" => Ok(Some(StreetNamePostType::LIGHTS)),
        "LF" => Ok(Some(StreetNamePostType::LOAF)),
        "LCK" => Ok(Some(StreetNamePostType::LOCK)),
        "LCKS" => Ok(Some(StreetNamePostType::LOCKS)),
        "LDG" => Ok(Some(StreetNamePostType::LODGE)),
        "LOOP" => Ok(Some(StreetNamePostType::LOOP)),
        "MALL" => Ok(Some(StreetNamePostType::MALL)),
        "MNR" => Ok(Some(StreetNamePostType::MANOR)),
        "MNRS" => Ok(Some(StreetNamePostType::MANORS)),
        "MDW" => Ok(Some(StreetNamePostType::MEADOW)),
        "MDWS" => Ok(Some(StreetNamePostType::MEADOWS)),
        "MEWS" => Ok(Some(StreetNamePostType::MEWS)),
        "ML" => Ok(Some(StreetNamePostType::MILL)),
        "MLS" => Ok(Some(StreetNamePostType::MILLS)),
        "MSN" => Ok(Some(StreetNamePostType::MISSION)),
        "MTWY" => Ok(Some(StreetNamePostType::MOTORWAY)),
        "MT" => Ok(Some(StreetNamePostType::MOUNT)),
        "MTN" => Ok(Some(StreetNamePostType::MOUNTAIN)),
        "MTNS" => Ok(Some(StreetNamePostType::MOUNTAINS)),
        "NCK" => Ok(Some(StreetNamePostType::NECK)),
        "ORCH" => Ok(Some(StreetNamePostType::ORCHARD)),
        "OVAL" => Ok(Some(StreetNamePostType::OVAL)),
        "OPAS" => Ok(Some(StreetNamePostType::OVERPASS)),
        "PARK" => Ok(Some(StreetNamePostType::PARK)),
        "PKWY" => Ok(Some(StreetNamePostType::PARKWAY)),
        "PASS" => Ok(Some(StreetNamePostType::PASS)),
        "PSGE" => Ok(Some(StreetNamePostType::PASSAGE)),
        "PATH" => Ok(Some(StreetNamePostType::PATH)),
        "PIKE" => Ok(Some(StreetNamePostType::PIKE)),
        "PNE" => Ok(Some(StreetNamePostType::PINE)),
        "PNES" => Ok(Some(StreetNamePostType::PINES)),
        "PL" => Ok(Some(StreetNamePostType::PLACE)),
        "PLN" => Ok(Some(StreetNamePostType::PLAIN)),
        "PLNS" => Ok(Some(StreetNamePostType::PLAINS)),
        "PLZ" => Ok(Some(StreetNamePostType::PLAZA)),
        "PT" => Ok(Some(StreetNamePostType::POINT)),
        "PTS" => Ok(Some(StreetNamePostType::POINTS)),
        "PRT" => Ok(Some(StreetNamePostType::PORT)),
        "PRTS" => Ok(Some(StreetNamePostType::PORTS)),
        "PR" => Ok(Some(StreetNamePostType::PRAIRIE)),
        "RADL" => Ok(Some(StreetNamePostType::RADIAL)),
        "RAMP" => Ok(Some(StreetNamePostType::RAMP)),
        "RNCH" => Ok(Some(StreetNamePostType::RANCH)),
        "RPD" => Ok(Some(StreetNamePostType::RAPID)),
        "RPDS" => Ok(Some(StreetNamePostType::RAPIDS)),
        "RST" => Ok(Some(StreetNamePostType::REST)),
        "RDG" => Ok(Some(StreetNamePostType::RIDGE)),
        "RDGS" => Ok(Some(StreetNamePostType::RIDGES)),
        "RIV" => Ok(Some(StreetNamePostType::RIVER)),
        "RD" => Ok(Some(StreetNamePostType::ROAD)),
        "RDS" => Ok(Some(StreetNamePostType::ROADS)),
        "RTE" => Ok(Some(StreetNamePostType::ROUTE)),
        "ROW" => Ok(Some(StreetNamePostType::ROW)),
        "RUE" => Ok(Some(StreetNamePostType::RUE)),
        "RUN" => Ok(Some(StreetNamePostType::RUN)),
        "SHL" => Ok(Some(StreetNamePostType::SHOAL)),
        "SHLS" => Ok(Some(StreetNamePostType::SHOALS)),
        "SHR" => Ok(Some(StreetNamePostType::SHORE)),
        "SHRS" => Ok(Some(StreetNamePostType::SHORES)),
        "SKWY" => Ok(Some(StreetNamePostType::SKYWAY)),
        "SPG" => Ok(Some(StreetNamePostType::SPRING)),
        "SPGS" => Ok(Some(StreetNamePostType::SPRINGS)),
        "SPUR" => Ok(Some(StreetNamePostType::SPUR)),
        "SQ" => Ok(Some(StreetNamePostType::SQUARE)),
        "SQS" => Ok(Some(StreetNamePostType::SQUARES)),
        "STA" => Ok(Some(StreetNamePostType::STATION)),
        "STRA" => Ok(Some(StreetNamePostType::STRAVENUE)),
        "STRM" => Ok(Some(StreetNamePostType::STREAM)),
        "ST" => Ok(Some(StreetNamePostType::STREET)),
        "STS" => Ok(Some(StreetNamePostType::STREETS)),
        "SMT" => Ok(Some(StreetNamePostType::SUMMIT)),
        "TER" => Ok(Some(StreetNamePostType::TERRACE)),
        "TRWY" => Ok(Some(StreetNamePostType::THROUGHWAY)),
        "TRCE" => Ok(Some(StreetNamePostType::TRACE)),
        "TRAK" => Ok(Some(StreetNamePostType::TRACK)),
        "TRFY" => Ok(Some(StreetNamePostType::TRAFFICWAY)),
        "TRL" => Ok(Some(StreetNamePostType::TRAIL)),
        "TRLR" => Ok(Some(StreetNamePostType::TRAILER)),
        "TUNL" => Ok(Some(StreetNamePostType::TUNNEL)),
        "TPKE" => Ok(Some(StreetNamePostType::TURNPIKE)),
        "UPAS" => Ok(Some(StreetNamePostType::UNDERPASS)),
        "UN" => Ok(Some(StreetNamePostType::UNION)),
        "UNS" => Ok(Some(StreetNamePostType::UNIONS)),
        "VLY" => Ok(Some(StreetNamePostType::VALLEY)),
        "VLYS" => Ok(Some(StreetNamePostType::VALLEYS)),
        "VIA" => Ok(Some(StreetNamePostType::VIADUCT)),
        "VW" => Ok(Some(StreetNamePostType::VIEW)),
        "VWS" => Ok(Some(StreetNamePostType::VIEWS)),
        "VLG" => Ok(Some(StreetNamePostType::VILLAGE)),
        "VLGS" => Ok(Some(StreetNamePostType::VILLAGES)),
        "VL" => Ok(Some(StreetNamePostType::VILLE)),
        "VIS" => Ok(Some(StreetNamePostType::VISTA)),
        "WALK" => Ok(Some(StreetNamePostType::WALK)),
        "WALL" => Ok(Some(StreetNamePostType::WALL)),
        "WAY" => Ok(Some(StreetNamePostType::WAY)),
        "WAYS" => Ok(Some(StreetNamePostType::WAYS)),
        "WL" => Ok(Some(StreetNamePostType::WELL)),
        "WLS" => Ok(Some(StreetNamePostType::WELLS)),
        _ => Ok(None),
    }
}
