name: Build, check and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Build and test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Build
        run: rustup update stable && rustup default stable
      - run: cargo build --verbose --all --features ci
      - name: Tests
        run: rustup update stable && rustup default stable
      - run: cargo test --verbose --features ci

  fmt:
    name: Format
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Rustfmt check
        run: rustup update stable && rustup default stable
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - run: rustup update stable && rustup default stable
      - run: rustup component add clippy
      - name: Clippy check
        run: rustup update stable && rustup default stable
      - run: cargo clippy --all -- -D warnings
